name: lintingpackage
description: "A new Flutter package project."
publish_to: none
version: 0.0.1
homepage:

environment:
  sdk: ^3.3.4

dependencies:
  # lints: ^4.0.0
  # Code is not allowed in this package. Do not add any dependencies or dev_dependencies.

# topics:
  # - lints
